version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-patterns:
      - "elasticsearch*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

