version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@elasticsearch*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

